### PR TITLE
Update link to repo in README.md

### LINKED ISSUE #4: Change link to repo in README

### PR DESCRIPTION
**Pull request by bvavrik**
closes #4

### CODE REVIEW

**Comment by blazekadam** [comment]
Please target dev instead of master.

**Comment by FloopCZ** [comment]
This seems to be a misunderstanding. The development installation is only useful if you want to edit the `cxflow` source codes and immediately try your changes (i.e., it is meant to be used when you develop `cxflow`). It is not meant to be used if you want to develop your project which __uses__ `cxflow`, for that you should use the standard installation. I do not believe that we should change the url to https, since than your changes cannot be pushed to the repo.

@blazekadam @petrbel Maybe we should not give the development installation to the public readme, since it is only useful for those that have the rights to push.

**Comment by blazekadam** [comment]
I would either move the dev install instructions to the contributors guide (which does not exist yet) or remove them entirely. 

No opinion regarding git vs. https url. I thought it's equivalent. If not, why to change to https?

**Comment by FloopCZ** [comment]
@blazekadam Agreed.

`git` allows you to use SSH certificate to log in. With `https`, you have to enter login and password manually. On the other hand, if the remote repo is public and you don't want to push into it, `https` won't ask you for the login at all.

Anyway, since we want the development installation instructions to disappear from the `README.md`, this PR is no longer relevant and I suggest closing it. Moreover, the development installation should not use `https`.

**Comment by blazekadam** [comment]
@FloopCZ agree

**Pull request closed without merging**
