### PR TITLE
Allow to specify restoration folder and model in single path

### LINKED ISSUE #75: Allow to specify `restore_path` instead of `restore_from` and `restore_model_name`
Requiring to specify `restore_model_name` is cumbersome and unnecessary, we should allow to specify the path at once.

### PR DESCRIPTION
**Pull request by luxusko**
Resolves #75

### CODE REVIEW

**Comment by luxusko** [comment]
Alternative new restoration command is `cxflow resume config_path folder_path/model.ckpt`

**Comment by petrbel** [comment]
The original idea was allowing a user to restore from a checkpoint and different config. I guess we don't need this feature anymore.

**Comment by blazekadam** [comment]
You can still do it @petrbel . It just merges checkpoint directory `restore_from` and checkpoint name (`model.restore_model_name`). Now you can either specify a dir only (if there is only one checkpoint) or the full checkpoint path.

My point is we do not need to keep the `model.restore_model_name` option.

**Comment by petrbel** [comment]
I probably didn't express myself clearly. What I meant was using the checkpoint from one directory (`log/...`) and config from another (`infer-configs/myconfig.yaml`).

However, I still think:
> I guess we don't need this feature anymore.

**Comment by blazekadam** [comment]
Oh, you did. My bad.

Well, this does not affect that feature anyways.

**Comment by blazekadam** [comment]
@luxusko can you finish it pls?

**Comment by luxusko** [comment]
Uff, sorry about leaving this open - it should be all right now, is it?

**Comment by petrbel** [comment]
@luxusko  @blazekadam should't also cxflow cli be updated? It's still weird to use `sch -- cxflow predict <model> <model>`

https://github.com/Cognexa/cxflow/blob/dev/cxflow/cli/args.py#L28

**Pull request merged**
